bcgov/citz-imb-sso-react

README.md

Update readme download link

---

src/state/useKeycloak.ts
src/types.ts

Added isAuthenticated boolean to useKeycloak hook

Added isAuthenticated boolean to useKeycloak hook

---

README.md
src/state/useKeycloak.ts
src/types.ts
src/utils.ts

- hasRole parameters now acts like protectedRoute parameters from citz-imb-kc-express package.
- can check for multiple roles
- **BREAKING**: changed parameter type from string to string array.

hasRole additions

---

README.md
src/state/useKeycloak.ts
src/types.ts

- Added User types.
- Removed console log from refreshToken function.
- Updated readme.

Add user types

---

package.json
src/state/useKeycloak.ts

[MVP-7](https://citz-imb.atlassian.net/jira/browse/MVP-7)
- A TypeError is thrown when idpHint isn't specified on login from useKeycloak

MVP-7: Fix for login TypeError

---

.github/workflows/release.yaml

[MVP-73](https://citz-imb.atlassian.net/jira/browse/MVP-73)
Fixed syntax error in workflow

MVP-73: Fix syntax error in github workflow

---

.github/workflows/release.yaml
README.md
package.json

[MVP-6](https://citz-imb.atlassian.net/jira/browse/MVP-6)
- Adds npm publish to release action
- Reset version number to 0.0.1 when locally pushed, then to 0.0.2 to test in actions

MVP-6: Add npm publish to release action

---

README.md
src/state/reducer.ts
src/state/useKeycloak.ts
src/types.ts

[MVP-11](https://citz-imb.atlassian.net/jira/browse/MVP-11)
- Adds isLoggedIn and isAuthenticated state
- Should set isLoggingIn when the user is attempting to login but hasn't yet completed the login process (like an isLoading state)
- isAuthenticated used to just check if user data was set, now it's its own state

MVP-11: Added isLoggingIn and isAuthenticated state

---

.github/workflows/release.yaml
README.md
package.json
src/components/Provider.tsx
src/components/RefreshExpiryDialog/index.tsx
src/components/RefreshExpiryDialog/styles.css
src/components/Wrapper.tsx
src/index.ts
src/state/reducer.ts
src/state/useSSO.ts
src/types.ts
src/utils.ts

[MVP-118](https://citz-imb.atlassian.net/jira/browse/MVP-118)
Renamed from `kc` and `keycloak` to `sso`

MVP-118: Rename to SSO

---

src/components/Provider.tsx
src/types.ts

[MVP-127](https://citz-imb.atlassian.net/jira/browse/MVP-127)
- Added `overrideShowRefreshExpiryDialog` which when true will show the `RefreshExpiryDialog` for testing purposes.
- Updated Wiki TypeScript Types

MVP-127: Added overrideShowRefreshExpiryDialog prop to ProviderProps

---

src/state/useSSO.ts

[MVP-77](https://citz-imb.atlassian.net/jira/browse/MVP-77)
Fixed issue with undefined user on useSSO hook

MVP-77: Fixed issue with undefined user on useSSO hook

---

README.md
package.json
src/components/Wrapper.tsx
src/state/useSSO.ts

Updating version to 1.0.0-alpha

---

package.json
src/components/Wrapper.tsx

- Updated to `alpha2`
- Added debug statement
- Changed useEffect dependency in Wrapper
Tested in `CoCo` app

Alpha2: Added debug statement

---

package.json
src/components/RefreshExpiryDialog/index.tsx
src/components/RefreshExpiryDialog/styles.css

- Made styles fit bcgov styles better
- Added BCSans font

Updated refresh dialog styles

---

package.json

[MVP-171](https://citz-imb.atlassian.net/jira/browse/MVP-171)
ESLint still works and package builds without error.

MVP-171: Updated dependencies

---

package.json
src/components/Provider.tsx
src/components/Wrapper.tsx
src/state/useSSO.ts
src/types.ts

[MVP-126](https://citz-imb.atlassian.net/jira/browse/MVP-126)
- Added `postLoginRedirectURL` prop to login.

MVP-126: Login redirect

---

docs/test.txt

[MVP-180](https://citz-imb.atlassian.net/browse/MVP-180)
Need a folder to host the devhub documentation. 

MVP-180 Add Devhub Documentation Folder

---

package.json
src/components/Wrapper.tsx

[MVP-188](https://citz-imb.atlassian.net/jira/browse/MVP-188)
- Fixed issue where user was logged out when page refreshed.
- Updated version to alpha5
This does re-introduce a console error because a 401 is returned after logout but this is only shown in react strict mode in dev and it doesnt cause any actual errors.

MVP-188: Fixed logout issue

---

.github/workflows/publish-techdocs.yaml

[MVP-180](https://citz-imb.atlassian.net/browse/MVP-180)
Testing the publish techdocs workflow 

PIMS-180 DevHub Doc Test

---

.github/workflows/publish-techdocs.yaml

format
[MVP-180](https://citz-imb.atlassian.net/jira/browse/MVP-180)

MVP-180 update to publish techdocs workflow

---

__tests__/unit/state/useSSO.test.tsx
package.json

- Omitted `eslint` updates because of peer dependency issues.
- Updated incorrect test case.
Package builds without errors and tests pass.

Dependency updates

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

[MVP-217](https://citz-imb.atlassian.net/jira/browse/MVP-217)

MVP-217: Update issue templates

---

catalog-info.yaml
mkdocs.yml
techdocs/docs/authentication-flow.md
techdocs/docs/index.md

[MVP-180](https://citz-imb.atlassian.net/jira/browse/MVP-180)

MVP-180: Finishing touches

---

mkdocs.yml

mkdocs path fix for flow diagram

---

package.json

Rolling back @testing-library/react

Release Fix

---

techdocs/docs/getting-started/quick-start-guide.md
techdocs/docs/index.md
techdocs/docs/purpose-and-benefits.md

Polishing techdocs
To see in devhub env please click: https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package

updating docs

---

__tests__/__mocks__/useSSO.ts
__tests__/unit/components/Provider.test.tsx
__tests__/unit/components/Wrapper.test.tsx
package.json
src/components/Wrapper.tsx
src/state/useSSO.ts
src/types.ts

[MVP-215](https://citz-imb.atlassian.net/jira/browse/MVP-215)
- Updated tests
- isLoggingIn state is now triggered after returning from the sso login page

MVP-215: Fixed isLoggingIn state

---

mkdocs.yml
techdocs/docs/using-the-package/troubleshooting.md

[MVP-240](https://citz-imb.atlassian.net/jira/browse/MVP-240)
View the changes at https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package/using-the-package/troubleshooting/

MVP-240: Added Troubleshooting page to techdocs

---

.github/workflows/publish-techdocs.yaml

testing techdocs publish action

---

.github/workflows/publish-techdocs.yaml
techdocs/docs/index.md

adding these changes so that the prod documentation will be built 

Modifying techdoc Workflow to Publish on Push to Main

---

techdocs/docs/index.md

Remove test whitespace index.md

---

.github/workflows/publish-techdocs.yaml

Revert back to release to publish

---

__tests__/__mocks__/useSSO.ts
__tests__/unit/state/reducer.test.ts
__tests__/unit/state/useSSO.test.tsx
src/components/Wrapper.tsx
src/state/reducer.ts
src/state/useSSO.ts
src/types.ts

[MVP-232](https://citz-imb.atlassian.net/jira/browse/MVP-232)
Changed isAuthenticated and isLoggingIn state to use sessionStorage so that they are retained between page loads

MVP-232: Set sessionStorage state

---

package.json

[MVP-232](https://citz-imb.atlassian.net/jira/browse/MVP-232)
Updating version to 1.0.0 so we can test the new release workflow and this will be released as `1.0.0-beta`

MVP-232: Update version

---

.github/workflows/release.yaml

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)

MVP-245: Release workflow tweaks

---

.github/workflows/release.yaml

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)
Action was failing because it needed to pull before pushing

MVP-245: Added git pull

---

README.md

[MVP-263](https://citz-imb.atlassian.net/jira/browse/MVP-263)

MVP-263: Updated documentation links in README

---

.github/helpers/package-release/check-npm-for-beta-version.cjs
.github/helpers/package-release/check-npm-for-version-tag.cjs
.github/helpers/package-release/validate-for-rc-tag.cjs
.github/helpers/package-release/validate-for-release-tag.cjs
.github/workflows/release.yaml

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)
Added guards to ensure proper use of the workflow.

MVP-245: Create Release guards

---

__tests__/unit/components/Provider.test.tsx
__tests__/unit/components/Wrapper.test.tsx
__tests__/unit/state/useSSO.test.tsx
__tests__/unit/utils/decodeJWT.test.ts
__tests__/unit/utils/hasRoles.test.ts
__tests__/unit/utils/normalizeUser.test.ts
package.json
rollup.config.js
src/components/Provider.tsx
src/utils/checkForUpdates.ts
src/utils/decodeJWT.ts
src/utils/hasRoles.ts
src/utils/index.ts
src/utils/normalizeUser.ts
tsconfig.json

[MVP-269](https://citz-imb.atlassian.net/jira/browse/MVP-269)
- Separated utils into their own files
- Added check that runs on Provider component mount to check for updates to the package
- Updated tests

MVP-269: update notification

---

techdocs/docs/index.md

[MVP-271](https://citz-imb.atlassian.net/jira/browse/MVP-271)
View at https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package

MVP-271: Added Package Management Plan link

---

README.md

[MVP-279](https://citz-imb.atlassian.net/jira/browse/MVP-279)

MVP-279: Updated links in README

---

scripts/bump-version.mjs

[MVP-245](https://citz-imb.atlassian.net/jira/browse/MVP-245)
Changed `let` to `const`

MVP-245: Tweaks to bump script

---

mkdocs.yml
techdocs/docs/getting-started/quick-start-guide.md
techdocs/docs/using-the-package/apis-&-components/provider.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/fetch-protected-route.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/get-auth-header-value.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/has-roles.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/is-authenticated.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/login.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/logout.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/user.md
techdocs/docs/using-the-package/apis-&-components/usesso.md
techdocs/docs/using-the-package/calling-a-protected-route.md
techdocs/docs/using-the-package/getting-user-information.md
techdocs/docs/using-the-package/typescript-types.md

[MVP-274](https://citz-imb.atlassian.net/jira/browse/MVP-274)
Added docs for the components and hooks like how MUI does their component docs.
View @ https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package/

MVP-274: Component docs

---

.github/workflows/ci-unit-integration-test.yaml

[MVP-266](https://citz-imb.atlassian.net/jira/browse/MVP-266)

MVP-266: Create CI Action to Run Test Suite on PR Open

---

jest.config.ts

[MVP-266](https://citz-imb.atlassian.net/jira/browse/MVP-266)

MVP-266: Updated jest config

---

README.md

[MVP-266](https://citz-imb.atlassian.net/jira/browse/MVP-266)

MVP-266: Code Climate Badges

---

mkdocs.yml
techdocs/docs/major-release-1.md
techdocs/docs/major-releases/major-release-1.md

[MVP-273](https://citz-imb.atlassian.net/jira/browse/MVP-273)
https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package/

MVP-273: Added Major Release page

---

.github/helpers/techdocs/update-main-typescript-types.cjs
.github/helpers/techdocs/update-typescript-types.cjs
.github/workflows/document-techdoc-types.yaml
.github/workflows/publish-techdocs.yaml
techdocs/docs/using-the-package/apis-&-components/provider.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/has-roles.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/login.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/logout.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/user.md
techdocs/docs/using-the-package/apis-&-components/usesso.md
techdocs/docs/using-the-package/typescript-types.md

[MVP-300](https://citz-imb.atlassian.net/jira/browse/MVP-300)
Scripts that run on push of source code. If the typescript types change, they will be updated where they are referenced in the docs.
Scripts can be run locally to test. Change the content of the typescript code blocks and run the script to watch it update them.

MVP-300: Automated TypeScript docs

---

techdocs/docs/using-the-package/apis-&-components/provider.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/fetch-protected-route.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/has-roles.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/login.md
techdocs/docs/using-the-package/apis-&-components/usesso-actions/logout.md

Same as requested for the css api component docs
https://dev.developer.gov.bc.ca/docs/default/component/citz-imb-sso-react-npm-package/

MVP-274: Techdoc Formatting Changes

---

.codeclimate.yaml

[MVP-344](https://citz-imb.atlassian.net/jira/browse/MVP-344)

MVP-344: Add Code Climate Config

---

.codeclimate.yaml

[MVP-355(https://citz-imb.atlassian.net/jira/browse/MVP-355)

MVP-355: Add Plugins to Code Climate Config

---

.github/workflows/publish-techdocs.yaml

[MVP-339](https://citz-imb.atlassian.net/jira/browse/MVP-339)
Had to change the release type after reading the docs.

MVP-339: Updated techdoc publish

---

.github/helpers/github-api/create-and-close-existing-issue.mjs
.github/helpers/github-api/github-api-requests.mjs
.github/helpers/npm-audit/create-report-issues.cjs
.github/helpers/npm-deps/create-report-issues.cjs

[MVP-318](https://citz-imb.atlassian.net/jira/browse/MVP-318)
Trying to fix an issue with creating the Issues for npm dep and vul reports. Seems like oktokit is now an esmodule and so it must be imported instead of using require.

MVP-318: Converted github api helpers to ModuleJS

---

.github/helpers/npm-audit/create-report.cjs
.github/helpers/npm-audit/run-npm-audit.cjs

[MVP-318](https://citz-imb.atlassian.net/jira/browse/MVP-318)
Will test once merged. This accounts for when via property has more than one array item, where as before it just grabbed the first item.

MVP-318: Fix vulnerability report

---

.github/helpers/npm-audit/create-report.cjs
.github/helpers/npm-audit/run-npm-audit.cjs

[MVP-318](https://citz-imb.atlassian.net/jira/browse/MVP-318)
- Fixed logic so "Highest Severity" text will not show when there are no vulnerabilities.

MVP-318: Vuln Report Fixes
